dataset_with_color_maps:
  images_dir: "../Data/FBA_dataset/train/images"
  color_maps_dir: "../Data/FBA_dataset/train/masks"
  metadata_dir: "../Data/FBA_dataset/metadata.json"

image_labeler:
  tool_class: "insert"
  coco_annotations_path: "../Data/FBA_dataset/train/images/train_labels.json"
  
dataloader:
  images_to_be_resized_path: "../Data/FBA_dataset/train/images"
  resized_images_dir: "../Data/resized_fba_with_lanczos_wo_wearscores_refactoredlabels"
  huggingface_dataset_link: "artisanalwasp/resized_fba_with_lanczos_wo_wearscores_refactoredlabels"
  generated_images_dir: "../Data/FBA_dataset/generated/bue/gen15/generated_15"